image:
  - Visual Studio 2022
  - Ubuntu2004

platform: x64

configuration: Release

clone_depth: 1

install:
  - cmd: call "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvars64.bat"

build_script:
  - cmd: cd %APPVEYOR_BUILD_FOLDER%/example/diff
  - cmd: msvc.bat
  - cmd: cd %APPVEYOR_BUILD_FOLDER%/example/suffix_tree_viz
  - cmd: msvc.bat
  - sh: cd %APPVEYOR_BUILD_FOLDER%
  - sh: doxygen Doxyfile

test_script:
  - cmd: cd %APPVEYOR_BUILD_FOLDER%/test
  - cmd: msvc.bat
