language: cpp
sudo: true
os: linux
dist: jammy
git:
  depth: 1
addons:
  apt:
    packages:
    - g++
    - doxygen
script:
- cd $TRAVIS_BUILD_DIR/example/diff
- chmod u+x ./gcc.sh
- ./gcc.sh
- cd $TRAVIS_BUILD_DIR/example/suffix_tree_viz
- chmod u+x ./gcc.sh
- ./gcc.sh
- cd $TRAVIS_BUILD_DIR/test
- chmod u+x ./gcc.sh
- ./gcc.sh
- cd $TRAVIS_BUILD_DIR
- doxygen Doxyfile
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: html
  github_token: $GH_REPO_TOKEN
  on:
    branch: main
