name: build
on:
  push:
    branches: [ main ]
jobs:
  run-on-ubuntu:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dir: ['./example/diff', './example/suffix_tree_viz', './test']
        compiler: ['clang++-16', 'g++']
    steps:
      - uses: actions/checkout@v3
      - uses: egor-tensin/setup-clang@v1
      - working-directory: ${{ matrix.dir }}
        run: |
          chmod u+x ./gcc.sh
          ./gcc.sh ${{ matrix.compiler }}
  run-on-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        dir: ['./example/diff', './example/suffix_tree_viz', './test']
    steps:
      - uses: actions/checkout@v3
      - uses: ilammy/msvc-dev-cmd@v1
      - working-directory: ${{ matrix.dir }}
        run: Invoke-Expression ./msvc.bat
